package com.example.kotlinpeliculas.entities

import io.ktor.client.*
import io.ktor.client.features.*
import io.ktor.client.features.json.JsonFeature
import io.ktor.client.request.*
import io.ktor.http.*

data class Pokemon(
    val numId : Int,
    val nombrePokemon: String,
    val tipoPokemon: String
) {
    companion object{
        val dataPokemon = mutableListOf(
            Pokemon(1,"Bulbasaur","Planta"),
            Pokemon(2,"Ivysaur","Planta"),
            Pokemon(3,"Venusaur","Planta"),
            Pokemon(4,"Charmander","Fuego"),
            Pokemon(5,"Charmeleon","Fuego"),
            Pokemon(6,"Charizard","Fuego"),
            Pokemon(7,"Squirtle","Agua"),
            Pokemon(8,"Wartortle","Agua"),
            Pokemon(9,"Blastoise","Agua"),
            Pokemon(10,"Caterpie","Bicho"),
            Pokemon(11,"Metapod","Bicho"),
            Pokemon(12,"Butterfree","Bicho"),
            Pokemon(13,"Weedle","Bicho"),
            Pokemon(14,"Kakuna","Bicho"),
            Pokemon(15,"Beedrill","Bicho"),
            Pokemon(16,"Pidgey","Normal"),
            Pokemon(17,"Pidgeotto","Normal"),
            Pokemon(18,"Pidgeot","Normal"),
            Pokemon(19,"Rattata","Normal"),
            Pokemon(20,"Raticate","Normal"),
            Pokemon(21,"Spearow","Normal"),
            Pokemon(22,"Fearow","Normal"),
            Pokemon(23,"Ekans","Veneno"),
            Pokemon(24,"Arbok","Veneno"),
            Pokemon(25,"Pikachu","Eléctrico"),
            Pokemon(26,"Raichu","Eléctrico"),
            Pokemon(27,"Sandshrew","Tierra"),
            Pokemon(28,"Sandslash","Tierra"),
            Pokemon(29,"Nidoran♀","Veneno"),
            Pokemon(30,"Nidorina","Veneno"),
            Pokemon(31,"Nidoqueen","Veneno"),
            Pokemon(32,"Nidoran♂","Veneno"),
            Pokemon(33,"Nidorino","Veneno"),
            Pokemon(34,"Nidoking","Veneno"),
            Pokemon(35,"Clefairy","Hada2"),
            Pokemon(36,"Clefable","Hada3"),
            Pokemon(37,"Vulpix","Fuego"),
            Pokemon(38,"Ninetales","Fuego"),
            Pokemon(39,"Jigglypuff","Normal"),
            Pokemon(40,"Wigglytuff","Normal"),
            Pokemon(41,"Zubat","Veneno"),
            Pokemon(42,"Golbat","Veneno"),
            Pokemon(43,"Oddish","Planta"),
            Pokemon(44,"Gloom","Planta"),
            Pokemon(45,"Vileplume","Planta"),
            Pokemon(46,"Paras","Bicho"),
            Pokemon(47,"Parasect","Bicho"),
            Pokemon(48,"Venonat","Bicho"),
            Pokemon(49,"Venomoth","Bicho"),
            Pokemon(50,"Diglett","Tierra"),
            Pokemon(51,"Dugtrio","Tierra"),
            Pokemon(52,"Meowth","Normal"),
            Pokemon(53,"Persian","Normal"),
            Pokemon(54,"Psyduck","Agua"),
            Pokemon(55,"Golduck","Agua"),
            Pokemon(56,"Mankey","Lucha"),
            Pokemon(57,"Primeape","Lucha"),
            Pokemon(58,"Growlithe","Fuego"),
            Pokemon(59,"Arcanine","Fuego"),
            Pokemon(60,"Poliwag","Agua"),
            Pokemon(61,"Poliwhirl","Agua"),
            Pokemon(62,"Poliwrath","Agua"),
            Pokemon(63,"Abra","Psíquico"),
            Pokemon(64,"Kadabra","Psíquico"),
            Pokemon(65,"Alakazam","Psíquico"),
            Pokemon(66,"Machop","Lucha"),
            Pokemon(67,"Machoke","Lucha"),
            Pokemon(68,"Machamp","Lucha"),
            Pokemon(69,"Bellsprout","Planta"),
            Pokemon(70,"Weepinbell","Planta"),
            Pokemon(71,"Victreebel","Planta"),
            Pokemon(72,"Tentacool","Agua"),
            Pokemon(73,"Tentacruel","Agua"),
            Pokemon(74,"Geodude","Roca"),
            Pokemon(75,"Graveler","Roca"),
            Pokemon(76,"Golem","Roca"),
            Pokemon(77,"Ponyta","Fuego"),
            Pokemon(78,"Rapidash","Fuego"),
            Pokemon(79,"Slowpoke","Agua"),
            Pokemon(80,"Slowbro","Agua"),
            Pokemon(81,"Magnemite","Eléctrico"),
            Pokemon(82,"Magneton","Eléctrico"),
            Pokemon(83,"Farfetchd","Normal"),
            Pokemon(84,"Doduo","Normal"),
            Pokemon(85,"Dodrio","Normal"),
            Pokemon(86,"Seel","Agua"),
            Pokemon(87,"Dewgong","Agua"),
            Pokemon(88,"Grimer","Veneno"),
            Pokemon(89,"Muk","Veneno"),
            Pokemon(90,"Shellder","Agua"),
            Pokemon(91,"Cloyster","Agua"),
            Pokemon(92,"Gastly","Fantasma"),
            Pokemon(93,"Haunter","Fantasma"),
            Pokemon(94,"Gengar","Fantasma"),
            Pokemon(95,"Onix","Roca"),
            Pokemon(96,"Drowzee","Psíquico"),
            Pokemon(97,"Hypno","Psíquico"),
            Pokemon(98,"Krabby","Agua"),
            Pokemon(99,"Kingler","Agua"),
            Pokemon(100,"Voltorb","Eléctrico"),
            Pokemon(101,"Electrode","Eléctrico"),
            Pokemon(102,"Exeggcute","Planta"),
            Pokemon(103,"Exeggutor","Planta"),
            Pokemon(104,"Cubone","Tierra"),
            Pokemon(105,"Marowak","Tierra"),
            Pokemon(106,"Hitmonlee","Lucha"),
            Pokemon(107,"Hitmonchan","Lucha"),
            Pokemon(108,"Lickitung","Normal"),
            Pokemon(109,"Koffing","Veneno"),
            Pokemon(110,"Weezing","Veneno"),
            Pokemon(111,"Rhyhorn","Tierra"),
            Pokemon(112,"Rhydon","Tierra"),
            Pokemon(113,"Chansey","Normal"),
            Pokemon(114,"Tangela","Planta"),
            Pokemon(115,"Kangaskhan","Normal"),
            Pokemon(116,"Horsea","Agua"),
            Pokemon(117,"Seadra","Agua"),
            Pokemon(118,"Goldeen","Agua"),
            Pokemon(119,"Seaking","Agua"),
            Pokemon(120,"Staryu","Agua"),
            Pokemon(121,"Starmie","Agua"),
            Pokemon(122,"Mr. Mime","Psíquico"),
            Pokemon(123,"Scyther","Bicho"),
            Pokemon(124,"Jynx","Hielo"),
            Pokemon(125,"Electabuzz","Eléctrico"),
            Pokemon(126,"Magmar","Fuego"),
            Pokemon(127,"Pinsir","Bicho"),
            Pokemon(128,"Tauros","Normal"),
            Pokemon(129,"Magikarp","Agua"),
            Pokemon(130,"Gyarados","Agua"),
            Pokemon(131,"Lapras","Agua"),
            Pokemon(132,"Ditto","Normal"),
            Pokemon(133,"Eevee","Normal"),
            Pokemon(134,"Vaporeon","Agua"),
            Pokemon(135,"Jolteon","Eléctrico"),
            Pokemon(136,"Flareon","Fuego"),
            Pokemon(137,"Porygon","Normal"),
            Pokemon(138,"Omanyte","Roca"),
            Pokemon(139,"Omastar","Roca"),
            Pokemon(140,"Kabuto","Roca"),
            Pokemon(141,"Kabutops","Roca"),
            Pokemon(142,"Aerodactyl","Roca"),
            Pokemon(143,"Snorlax","Normal"),
            Pokemon(144,"Articuno","Hielo"),
            Pokemon(145,"Zapdos","Eléctrico"),
            Pokemon(146,"Moltres","Fuego"),
            Pokemon(147,"Dratini","Dragón"),
            Pokemon(148,"Dragonair","Dragón"),
            Pokemon(149,"Dragonite","Dragón"),
            Pokemon(150,"Mewtwo","Psíquico"),
            Pokemon(151,"Mew","Psíquico")
        )


    }
}

suspend fun main() {
    val client = HttpClient {
        install(JsonFeature)
    }

    val url = "https://pokeapi.co/api/v2/pokemon/ditto"
    val response: String = client.get(url)

    println(response)

    client.close()
}